---
- name: InstallNeo4J
  hosts: all
  become: yes
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Ensure group "neo4j" exists
      group:
        name: neo4j
        state: present
        gid: 7474
        system: yes
    
    - name: Ensure user "neo4j" exists
      user:
        name: neo4j
        state: present
        uid: 7474
        system: yes
        create_home: no
        group: neo4j


    - name: Install OpenJDK and other tools
      apt:
        pkg:
        - curl
        - wget
        - gosu
        - jq
        - htop
        - tree
        - vim
        - openjdk-11-jdk
        state: present
        install_recommends: no

    - name: Remove Neo4J
      file:
        path: $NEO4J_HOME
        state: absent

    - name: Remove tar file
      file:
        path: /var/lib/neo4j-enterprise-4.1.3-unix.tar.gz
        state: absent

    - name: Remove /logs
      file:
        path: /logs
        state: absent

    - name: Remove /data
      file:
        path: /data
        state: absent

    - name: Download and Install Neo4J
      unarchive:
        src: https://dist.neo4j.org/neo4j-enterprise-4.1.3-unix.tar.gz
        dest: /var/lib
        remote_src: yes
        force: yes

    - copy:
        src: /var/lib/neo4j-enterprise-4.1.3/
        dest: ${NEO4J_HOME}
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/data
        dest: /data
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/logs
        dest: /logs
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes

    - name: Remove $NEO4J_HOME/data
      file:
        path: $NEO4J_HOME/data
        state: absent

    - name: Remove $NEO4J_HOME/logs
      file:
        path: $NEO4J_HOME/logs
        state: absent

    - name: Install Neo4J - Make Links
      file:
        src: /data
        dest: $NEO4J_HOME/data
        owner: neo4j
        group: neo4j
        state: link

    - name: Install Neo4J - Make Links
      file:
        src: /logs
        dest: $NEO4J_HOME/logs
        owner: neo4j
        group: neo4j
        state: link

    - git_config:
        name: user.email
        scope: global
        value: 'atingupta2005@gmail.com'

    - git_config:
        name: user.name
        scope: global
        value: 'Atin Gupta'

    - name: Commit Cofig to GIT
      shell:
        cmd: cd $NEO4J_HOME/conf && git init && git add * && git commit -am "-"

    - name: Copy restart-neo4j.sh
      copy:
        src: restart-neo4j.sh
        dest: ${NEO4J_HOME}/bin/restart-neo4j.sh
        owner: atin
        group: atin
        mode: '0777'
    - name: Copy neo4j-env-vars.sh
      copy:
        src: neo4j-env-vars.sh
        dest: /etc/profile.d/neo4j-env-vars.sh
        owner: root
        group: root
        mode: '0777'

    - name: Change file ownership, group and permissions - /data
      file:
        path: /data
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes

    - name: Change file ownership, group and permissions - /logs
      file:
        path: /logs
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes

    - name: Change file ownership, group and permissions - "${NEO4J_HOME}"
      file:
        path: "${NEO4J_HOME}"
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes
