---
- name: Cluster Configigure Neo4J
  hosts: neo4jservers
  become_user: neo4j
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Working for {{ inventory_hostname }}
      assemble:
       src: '{{ inventory_hostname }}.inc.neo4j.conf'
       dest: '${NEO4J_HOME}/conf/neo4j.conf'
       delimiter: '### Cluster Configuration ###'
       backup: yes
       remote_src: no