---
- name: Restart Neo4J
  hosts: neo4jservers
  serial: 1
  become_user: neo4j
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Stop Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/neo4j stop

    - name: Pause for 20 sec
      pause:
       seconds: 20

    - name: Start Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/neo4j start
    
