---
- name: Cluster Configigure Neo4J
  hosts: neo4jservers
  become_user: neo4j
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - copy:
        src: ${NEO4J_HOME}/data
        dest: /data
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - name: Copy restart-neo4j.sh
      copy:
        src: restart-neo4j.sh
        dest: ${NEO4J_HOME}/bin/restart-neo4j.sh
        owner: atin
        group: atin
        mode: '0777'