---
- name: InstallNeo4J
  hosts: neo4jservers
  become: yes
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install OpenJDK and other tools
      apt:
        pkg:
        - curl
        - wget
        - gosu
        - jq
        - htop
        - tree
        - vim
        - openjdk-11-jdk
        state: present
        install_recommends: no

    - name: Remove Neo4J
      shell:
        cmd: sudo rm -rf "${NEO4J_HOME}" /var/lib/neo4j-enterprise-4.1.3-unix.tar.gz  /data /logs

    - name: Download and Install Neo4J
      unarchive:
        src: https://dist.neo4j.org/neo4j-enterprise-4.1.3-unix.tar.gz
        dest: /var/lib
        remote_src: yes
        force: yes

    - copy:
        src: /var/lib/neo4j-enterprise-4.1.3
        dest: ${NEO4J_HOME}
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/data
        dest: /data
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/logs
        dest: /logs
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - name: Install Neo4J - Remove /data and /logs from NEO4J_HOME
      shell:
        cmd: sudo rm -rf "${NEO4J_HOME}"/data && sudo rm -rf "${NEO4J_HOME}"/logs
    - name: Install Neo4J - Make Links
      shell:
        cmd: ln -s /data "${NEO4J_HOME}"/data && ln -s /logs "${NEO4J_HOME}"/logs
    - name: Setup GIT
      shell:
        cmd: git config --global user.name `hostname` && git config --global user.email `hostname`@mail.com
    - name: Commit Cofig to GIT
      shell:
        cmd: cd $NEO4J_HOME/conf && git init && git add * && git commit -am "-"

    - name: Copy restart-neo4j.sh
      copy:
        src: ./resources/restart-neo4j.sh
        dest: ~/restart-neo4j.sh
        owner: atingupta2005
        group: root
        mode: '0777'
 
    - name: Create Group
      shell:
        cmd: addgroup --gid 7474 --system neo4j
    - name: Create User
      shell:
        cmd: adduser --uid 7474 --system --no-create-home --home "${NEO4J_HOME}" --ingroup neo4j neo4j