---
- name: InstallNeo4J
  hosts: neo4jservers
  become: yes
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Ensure group "neo4j" exists
      group:
        name: neo4j
        state: present
        gid: 7474
        system: yes
    
    - name: Ensure user "neo4j" exists
      user:
        name: neo4j
        state: present
        uid: 7474
        system: yes
        create_home: no
        group: neo4j


    - name: Install OpenJDK and other tools
      apt:
        pkg:
        - curl
        - wget
        - gosu
        - jq
        - htop
        - tree
        - vim
        - openjdk-11-jdk
        state: present
        install_recommends: no

    - name: Remove Neo4J
      shell:
        cmd: sudo rm -rf "${NEO4J_HOME}" /var/lib/neo4j-enterprise-4.1.3-unix.tar.gz  /data /logs

    - name: Download and Install Neo4J
      unarchive:
        src: https://dist.neo4j.org/neo4j-enterprise-4.1.3-unix.tar.gz
        dest: /var/lib
        remote_src: yes
        force: yes

    - copy:
        src: /var/lib/neo4j-enterprise-4.1.3/
        dest: ${NEO4J_HOME}
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/data
        dest: /data
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - copy:
        src: ${NEO4J_HOME}/logs
        dest: /logs
        owner: neo4j
        group: neo4j
        mode: 0777
        remote_src: yes
        force: yes
    - name: Install Neo4J - Remove /data and /logs from NEO4J_HOME
      shell:
        cmd: sudo rm -rf "${NEO4J_HOME}"/data && sudo rm -rf "${NEO4J_HOME}"/logs
    - name: Install Neo4J - Make Links
      shell:
        cmd: ln -s /data "${NEO4J_HOME}"/data && ln -s /logs "${NEO4J_HOME}"/logs
    - name: Setup GIT
      shell:
        cmd: git config --global user.name `hostname` && git config --global user.email `hostname`@mail.com
    - name: Commit Cofig to GIT
      shell:
        cmd: cd $NEO4J_HOME/conf && git init && git add * && git commit -am "-"

    - name: Copy restart-neo4j.sh
      copy:
        src: restart-neo4j.sh
        dest: ${NEO4J_HOME}/bin/restart-neo4j.sh
        owner: atin
        group: atin
        mode: '0777'
    - name: Copy neo4j-env-vars.sh
      copy:
        src: neo4j-env-vars.sh
        dest: /etc/profile.d/neo4j-env-vars.sh
        owner: root
        group: root
        mode: '0777'
    - name: Setup Permissions
      shell:
        cmd: sudo chown -R neo4j:neo4j /data && sudo chmod -R 777 /data && sudo chown -R neo4j:neo4j /logs && sudo chmod -R 777 /logs && sudo chown -R neo4j:neo4j "${NEO4J_HOME}" && sudo chmod -R 777 "${NEO4J_HOME}"
        