---
- name: Restart Neo4J
  hosts: neo4jservers
  become_user: neo4j
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Stop Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/neo4j stop

    - name: wait
      command: sleep 30
      throttle: 1

    - name: Start Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/neo4j start
    
