---
- name: Unbind Neo4J Cluster
  hosts: neo4jservers
  become: yes
  environment:
    NEO4J_HOME: /var/lib/neo4j

  tasks:
    - name: Change file ownership, group and permissions - /data
      file:
        path: /data
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes

    - name: Change file ownership, group and permissions - /var/lib/neo4j
      file:
        path: /var/lib/neo4j
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes

    - name: Stop Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/neo4j stop

    - name: Unbind from Cluster
      shell:
        cmd: /var/lib/neo4j/bin/neo4j-admin unbind

    - name: Remove /data/databases
      file:
        path: /data/databases
        state: absent

    - name: Remove /data/transactions
      file:
        path: /data/transactions
        state: absent

    - name: Remove /var/lib/neo4j/data
      file:
        path: /var/lib/neo4j/data
        state: absent

    - name: Create /var/lib/neo4j/data
      file:
        path: /var/lib/neo4j/data
        state: directory

    - name: Install Neo4J - Make Links
      file:
        src: /data
        dest: /var/lib/neo4j/data
        owner: neo4j
        group: neo4j
        state: link

    - name: Change file ownership, group and permissions - /data
      file:
        path: /data
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes

    - name: Change file ownership, group and permissions - /var/lib/neo4j
      file:
        path: /var/lib/neo4j
        owner: neo4j
        group: neo4j
        mode: '0777'
        recurse: yes


    - name: List /data
      find:
        paths: /data
    
    - name: Start Neo4J
      shell:
        cmd: /var/lib/neo4j/bin/restart-neo4j.sh
